export {
  MainText,
  MainTextWhite,
  SecondaryText,
  TertiaryText,
  HeaderColor,
  MIGreen,
  MIPink,
  AppBackgroundColors,
  OnboardingBackgroundColors,
  MatchGradient,
  PrimaryGrey,
  White,
  CompanyListGrey,
  SecondaryGrey,
  LimeGreen,
  Black,
} from './RegularTheme';
